env:
  es6: true
  node: true
parserOptions: 
  ecmaVersion: 2018
extends: 
    - airbnb-base
    - plugin:prettier/recommended
rules:
    "prefer-destructuring": ["error", {"object": true, "array": false}]
    "no-restricted-syntax": ["error", "WithStatement"]
    "no-await-in-loop": ["off"]
    "no-underscore-dangle": ["error", { "allow": ["_id"] }]
    "no-param-reassign": ["off"]
    "complexity": ["error", 7]
    "max-lines": ["error"]
    "max-lines-per-function": ["error"]
    "consistent-return": ["off"]
    "linebreak-style": ["off"]
overrides: 
  - files: [ "**.test.js", "__mocks__/**" ]
    plugins:
      - jest
    env:
      jest: true
    rules: 
      "jest/no-disabled-tests": "warn"
      "jest/no-focused-tests": "error"
      "jest/no-identical-title": "error"
      "jest/prefer-to-have-length": "warn"
      "jest/valid-expect": "error"
      "no-underscore-dangle": ["error", { "allow": ["_id"] }]
      "max-lines-per-function": ["off"]
      "max-lines": ["off"]
      "linebreak-style": ["off"]
  - files: [ "*.js" ]
    rules: 
      "no-console": "off"
