version: "3"
services:
  node-app:
    build: .
    container_name: "order-app"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    env_file: development.env

  mongo:
    image: "mongo"
    container_name: "orderDB"
