name: Node CI

on: 
  push:
    branches:
    - master

jobs:
  ci:

    runs-on: ubuntu-latest
    container:
      image: node

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: npm install and lint
      run: |
        npm ci
        npm run lint

  cd:
    
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nitsaw/node-app:latest
          build-args: |
            arg1=value1
            arg2=value2